test each commit using simple checkout

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -40,45 +40,47 @@ jobs:
         run: echo "FETCH_DEPTH=$((${{ github.event.pull_request.commits }} + 2))" >> "$GITHUB_ENV"
       - uses: actions/checkout@v4
         with:
-          ref: ${{ github.event.pull_request.head.sha }}
           fetch-depth: ${{ env.FETCH_DEPTH }}
-      - name: Determine commit range
+
+      - name: Get list of commits to test
+        id: commit-list
         run: |
-          # Checkout HEAD~ and find the test base commit
-          # Checkout HEAD~ because it would be wasteful to rerun tests on the PR
-          # head commit that are already run by other jobs.
-          git checkout HEAD~
-          # Figure out test base commit by listing ancestors of HEAD, excluding
-          # ancestors of the most recent merge commit, limiting the list to the
-          # newest MAX_COUNT ancestors, ordering it from oldest to newest, and
-          # taking the first one.
-          #
-          # If the branch contains up to MAX_COUNT ancestor commits after the
-          # most recent merge commit, all of those commits will be tested. If it
-          # contains more, only the most recent MAX_COUNT commits will be
-          # tested.
-          #
-          # In the command below, the ^@ suffix is used to refer to all parents
-          # of the merge commit as described in:
-          # https://git-scm.com/docs/git-rev-parse#_other_rev_parent_shorthand_notations
-          # and the ^ prefix is used to exclude these parents and all their
-          # ancestors from the rev-list output as described in:
-          # https://git-scm.com/docs/git-rev-list
-          MERGE_BASE=$(git rev-list -n1 --merges HEAD)
-          EXCLUDE_MERGE_BASE_ANCESTORS=
-          # MERGE_BASE can be empty due to limited fetch-depth
-          if test -n "$MERGE_BASE"; then
-            EXCLUDE_MERGE_BASE_ANCESTORS=^${MERGE_BASE}^@
+          git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1
+          # The default actions/checkout@v4 uses PR merge branch refs/pull/PULL_REQUEST_NUMBER/merge, a synthetic merge commit created by github to simulate merging PR branch into master.
+          # Therefore use `HEAD^2` in the merge-base calculation
+          MERGE_BASE=$(git merge-base ${{ github.event.pull_request.base.sha }} HEAD^2)
+          # Drop the top commit (last in the list) because it would be wasteful to rerun tests on the PR head commit that are already run by other jobs.
+          COMMITS=$(git rev-list --max-count=${{ env.MAX_COUNT }} --reverse ${MERGE_BASE}..${{ github.event.pull_request.head.sha }} | head -n -1)
+
+          if [ -z "$COMMITS" ]; then
+            echo "All commits filterd out. This probably indicates an error in the merge base or commit list calculations";
+            exit 1
           fi
-          echo "TEST_BASE=$(git rev-list -n$((${{ env.MAX_COUNT }} + 1)) --reverse HEAD $EXCLUDE_MERGE_BASE_ANCESTORS | head -1)" >> "$GITHUB_ENV"
-      - run: |
-          sudo apt-get update
-          sudo apt-get install clang ccache build-essential cmake ninja-build pkgconf python3-zmq libevent-dev libboost-dev libsqlite3-dev libdb++-dev systemtap-sdt-dev libzmq3-dev qt6-base-dev qt6-tools-dev qt6-l10n-tools libqrencode-dev -y
-      - name: Compile and run tests
+
+          echo "commits=$(echo "$COMMITS")" >> "$GITHUB_OUTPUT"
+          echo "Commits to be tested(s):"
+          echo "$COMMITS"
+
+      - name: Install dependencies
         run: |
-          # Run tests on commits after the last merge commit and before the PR head commit
-          # Use clang++, because it is a bit faster and uses less memory than g++
-          git rebase --exec "echo Running test-one-commit on \$( git log -1 ) && CC=clang CXX=clang++ cmake -B build -DWERROR=ON -DWITH_ZMQ=ON -DBUILD_GUI=ON -DBUILD_BENCH=ON -DBUILD_FUZZ_BINARY=ON -DWITH_BDB=ON -DWITH_USDT=ON -DCMAKE_CXX_FLAGS='-Wno-error=unused-member-function' && cmake --build build -j $(nproc) && ctest --output-on-failure --stop-on-failure --test-dir build -j $(nproc) && ./build/test/functional/test_runner.py -j $(( $(nproc) * 2 )) --combinedlogslen=99999999" ${{ env.TEST_BASE }}
+          sudo apt-get update
+          sudo apt-get install -y clang ccache build-essential cmake ninja-build pkgconf python3-zmq libevent-dev libboost-dev libsqlite3-dev libdb++-dev systemtap-sdt-dev libzmq3-dev qt6-base-dev qt6-tools-dev qt6-l10n-tools libqrencode-dev
+
+      - name: Build and test commit(s)
+        run: |
+          COMMITS="${{ steps.commit-list.outputs.commits }}"
+          echo "$COMMITS" | while read -r COMMIT; do
+            echo "Testing commit $COMMIT"
+            git checkout "$COMMIT" || { echo "Failed to checkout $COMMIT"; exit 1; }
+            # Use clang++, because it is a bit faster and uses less memory than g++
+            CC=clang CXX=clang++ cmake -B build -DWERROR=ON -DWITH_ZMQ=ON -DBUILD_GUI=ON -DBUILD_BENCH=ON -DBUILD_FUZZ_BINARY=ON -DWITH_BDB=ON -DWITH_USDT=ON -DCMAKE_CXX_FLAGS='-Wno-error=unused-member-function' || exit 1
+            cmake --build build -j $(nproc) || exit 1
+            ctest --output-on-failure --stop-on-failure --test-dir build -j $(nproc) || exit 1
+            ./build/test/functional/test_runner.py -j $(( $(nproc) * 2 )) --combinedlogslen=99999999 || exit 1
+            echo "Tests passed for commit $COMMIT"
+            rm -Rf build
+          done
+        shell: bash
 
   # macos-native-arm64:
   #   name: ${{ matrix.job-name }}
